version: '3'

services:
    # app:
    #     container_name: mern_shopping_list
    #     restart: always
    #     build: .
    #     ports:
    #         - '3001:3000'
    #     links:
    #         - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
        volumes: ['./data:/data/db']
        # environment: 
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: 12345678
        #     MONGO_INITDB_DATABASE: mern_shopping_list
